language: node_js
node_js:
  - 14
  - 11

cache: npm

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - libgstreamer-plugins-base1.0*
      - libgstreamer1.0-dev
      - libgstrtspserver-1.0-dev
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-base-apps
      - python3-gst-1.0
      - network-manager

install:
  - pip3 install --upgrade pip --user
  - pip3 --version
  - pip3 install future netifaces pymavlink --user
  - npm install

before_script:
  - git submodule update --init --recursive
  ## mavlink-router
  - cd ./modules/mavlink-router
  - ./autogen.sh
  - ./configure CFLAGS='-g -O2' --disable-systemd
  - make
  - sudo make install
  - cd ../../
  - sudo /etc/init.d/network-manager start

script:
  - npm run testback
  - npm run testfront
  - npm run build

