# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt update 
        sudo apt -y install libgstreamer-plugins-base1.0* libgstreamer1.0-dev libgstrtspserver-1.0-dev
        sudo apt -y install gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-base-apps
        sudo apt -y install python3-gst-1.0 network-manager
        pip3 --version
        pip3 install future netifaces pymavlink --user
        
    - name: Build mavlink-router
      run: |
        git submodule update --init --recursive
        cd ./modules/mavlink-router
        ./autogen.sh
        ./configure CFLAGS='-g -O2' --disable-systemd
        make
        sudo make install
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Run tests  
    - run: |
      npm run build --if-present
      npm run testback
      npm run testfront

    - name: Run Coveralls tests  
    - run: npm run test-cov


